server:
  port: 8086
spring:
  datasource:
    angelinaDataSource:
      url: jdbc:mysql://localhost:3306/arknights?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    servlet:
      multipart:
        # 单个文件最大限制 类型是datasize，单位kb
        max-file-size: 20480
        # 单次请求最大限制
        max-request-size: 20480
  redis:
    # 使用的数据库（0-15），默认为0
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
